# my-go-tools task-unit-tests.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: my-go-tools

outputs:
- name: coverage-results

run:
  path: ./my-go-tools/ci/scripts/unit-tests.sh
  # args: [-debug]
